((active-dirs ("hw3"))
 (inactive-dirs ())
 (port-number 7978)
 (allow-new-users #f)
 (allow-change-info #t)
 (allow-web-upload (".rkt" ".tar.gz" "tar" ".tar.bz2" ".zip"))
 (default-file-name "grades.rkt")
 (username-case-sensitive #t)
 (web-log-file "web.log")
 (log-file "stdout.log")
 (user-regexp #rx"^[.a-zA-Z0-9]+$")
 (extra-fields
  (("Full Name" #f #f)
   ("Email" #rx"^[^@<>\"`',]+@[a-zA-Z0-9_.-]+[.][a-zA-Z]+$" #f)))
 (master-password #f))
